name: PHP Standards
on:
  push:
    branches:
      - 'main'
    paths:
      - '**.php'
      - '**.json'
  pull_request:
    branches:
      - '**'
    paths:
      - '**.php'
      - '**.json'

jobs:
  build:
    name: PHP Coding Standards
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install PHP
        uses: shivammathur/setup-php@2.7.0
        with:
          php-version: '7.4'
          coverage: none

      - name: Echo PHP & Composer versions
        run: |
          php --version
          php -m
          composer --version

      - name: Get Composer Cache Directory
        id: composer-cache-dir
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache PHP Dependencies
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-composer-7.2-${{ hashFiles('composer.lock') }}

      - name: Install PHP Dependencies
        run: |
          composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: PHPCS cache
        uses: actions/cache@v2
        with:
          path: tests/cache
          key: ${{ runner.os }}-phpcs-7.2-${{ hashFiles('plugin.php') }}

      - name: Run the tests
        run: |
          composer lint
        env:
          MYSQL_DATABASE: wordpress
          WP_TESTS_DB_PASS: root
